function handleSubmit(getState, setState, newLongURL) {
    if (newLongURL !== getState().doc.long) {
        setState({
            doc: {
                long: newLongURL,
                short: "", // generated in backend
                id: "" // generated by mongoose
            },
            data: getState().data
        });
    } // don't allow the same URL to be entered more than once in succession
    // ( The same URL can be added more than once in the database )
}

export { handleSubmit };